"""adding a password to User

Revision ID: 03df0670bfda
Revises: d5a419fdbb72
Create Date: 2020-12-02 21:09:13.293213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03df0670bfda'
down_revision = 'd5a419fdbb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
