"""adding time

Revision ID: 5e666a2c8c59
Revises: 8c7499f96265
Create Date: 2020-09-20 22:20:40.562223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e666a2c8c59'
down_revision = '8c7499f96265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_author'), 'post', ['author'], unique=False)
    op.create_index(op.f('ix_post_text'), 'post', ['text'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_text'), table_name='post')
    op.drop_index(op.f('ix_post_author'), table_name='post')
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
